#!/usr/bin/env bash

pgrep -x sxhkd >/dev/null || sxhkd &

MONITORS=($(bspc query -M --names))
MONITOR=$(xrandr -q | grep primary | cut -d' ' -f1)

case ${#MONITORS[@]} in
1)
	bspc monitor -d I II III IV V VI VII VIII IX X
	;;
2)
	bspc monitor $MONITOR -d II III IV V VI VII VIII IX X
	;;
esac

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc config border_width 2
bspc config window_gap 12

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Emacs state=tiled

$HOME/.config/polybar/launch.sh
$HOME/.fehbg

wmname LG3D
