[packages.darwin]
taps = [
  "beeftornado/rmtree",
  "d12frosted/emacs-plus",
  "homebrew/bundle",
  "homebrew/cask-fonts",
  "homebrew/command-not-found",
  "homebrew/services",
  "jimeh/emacs-builds",
  "railwaycat/emacsmacport",
]
brews = [
  "antidote",
  "apktool",
  "aspell",
  "beancount",
  "black",
  "chezmoi",
  "coreutils",
  "curl",
  "fava",
  "fd",
  "fzf",
  "gcc",
  "git",
  { name = "gnupg", link = false },
  { name = "gnupg@2.2", link = true },
  "gradle",
  "graphviz",
  "homeassistant-cli",
  "htop",
  "imagemagick",
  "iperf3",
  "isync",
  "jdtls",
  "jq",
  "ki",
  "kotlin",
  "kotlin-language-server",
  "ktlint",
  "libgccjit",
  "libvterm",
  { name = "logrotate", restart_service = true },
  "mas",
  "mosh",
  "mu",
  "n",
  "neofetch",
  "neovim",
  "openapi-generator",
  "openjdk@11",
  "openjdk@17",
  "p7zip",
  "pass",
  "pass-otp",
  "pgformatter",
  "plantuml",
  "poetry",
  "pylint",
  "pyright",
  "python",
  "python-lsp-server",
  "ripgrep",
  "rust",
  "scrcpy",
  "starship",
  "swagger-codegen",
  "switchaudio-osx",
  "telnet",
  "tldr",
  "tokei",
  "tree-sitter",
  "wget",
  "xray",
  "you-get",
  "yt-dlp",
  "zig",
  "zsh-autosuggestions",
  "zsh-syntax-highlighting",
]
casks = [
  "android-file-transfer",
  "android-platform-tools",
  "anki",
  "appcleaner",
  "bilibili",
  "blackhole-16ch",
  "calibre",
  "codewhisperer",
  "deepl",
  "discord",
  "dozer",
  "font-cascadia-code",
  "font-dejavu",
  "font-fira-code",
  "font-inter",
  "font-iosevka",
  "font-iosevka-aile",
  "font-iosevka-etoile",
  "font-jetbrains-mono",
  "font-newsreader",
  "font-noto-sans",
  "font-noto-sans-math",
  "font-noto-serif",
  "font-roboto",
  "font-roboto-mono",
  "font-roboto-serif",
  "font-roboto-slab",
  "font-symbols-only-nerd-font",
  "font-victor-mono",
  "iina",
  "itsycal",
  "jetbrains-toolbox",
  "karabiner-elements",
  "kindle",
  "libreoffice",
  "logitech-options",
  "logseq",
  "lyricsx",
  "mactex-no-gui",
  "microsoft-edge",
  "microsoft-remote-desktop",
  "monitorcontrol",
  "mos",
  "motrix",
  "mpv",
  "neovide",
  "neteasemusic",
  "netnewswire",
  "nextcloud",
  "nutstore",
  "obsidian",
  "orbstack",
  "postman",
  "proxifier",
  "proxyman",
  "raycast",
  "rectangle",
  "sf-symbols",
  "spotify",
  "squirrel",
  "stats",
  "visual-studio-code",
  "wezterm",
  "wireshark",
  "xquartz",
  "zotero",
]

[packages.darwin.mas]
"Amphetamine" = 937984704
"Developer" = 640199958
"Final Cut Pro" = 424389933
"Immersive Translate" = 6447957425
"Juice" = 1478610778
"KeyPad" = 1491684442
"Logic Pro" = 634148309
"MainStage" = 634159523
"MenubarX" = 1575588022
"Microsoft Bing for Safari" = 1560727432
"Playgrounds" = 1496833156
"RSSHub Radar" = 1610744717
"The Unarchiver" = 425424353
"WeChat" = 836500024
"Xcode" = 497799835
