[path]
org = "Developer/Personal/org"
org-roam = "Developer/Personal/org-roam"
beancount = "Developer/Personal/beancount"
pass = "Developer/Personal/pass"

emacs = ".config/emacs"
proxy = ".config/proxy"
plum = ".config/plum"
isyncrc = ".config/isyncrc"

rime = ".local/share/rime"
