[path]
org = "Life/org"
org-roam = "Life/org-roam"
beancount = "Life/beancount"
pass = "Life/pass"

emacs = ".config/emacs"
proxy = ".config/proxy"
plum = ".config/plum"
isyncrc = ".config/isyncrc"

rime = ".local/share/rime"
